sudo: required
dist: xenial
addons:
  apt:
    sources:
      - mysql-5.7-xenial
    packages:
      - mysql-server
      - mysql-client

language: node_js
node_js: '8'
cache: yarn
before_install:
  # - sudo mysql_upgrade
  - sudo service mysql restart

script:
  - yarn build
  - yarn test

after_script:
  - sudo service mysql stop
