// flow-typed signature: a4ee7c148e18d3e82864960efb06bdc7
// flow-typed version: <<STUB>>/pegjs_v^0.10.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pegjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pegjs' {
  declare class PEGParser {
    parse(input: string): mixed;
  }

  declare export default {
    generate: (grammar: string) => PEGParser,
  };
}
