-- Simple expression (constants)
CREATE TABLE t1 (c1 INT GENERATED ALWAYS AS (0) VIRTUAL NOT NULL);
CREATE TABLE t2 (c1 INT GENERATED ALWAYS AS (1) VIRTUAL NOT NULL);
CREATE TABLE t3 (c1 TINYINT(1) GENERATED ALWAYS AS (TRUE) VIRTUAL NOT NULL);
CREATE TABLE t4 (c1 TINYINT(1) GENERATED ALWAYS AS (FALSE) VIRTUAL NOT NULL);
CREATE TABLE t5 (c1 VARCHAR(64) GENERATED ALWAYS AS ('why, hello') VIRTUAL NOT NULL);
CREATE TABLE t6 (c1 INT GENERATED ALWAYS AS (NULL) VIRTUAL)
