-- Make sure all syntaxes for GENERATED COLUMNS are supported
CREATE TABLE t1 (
  c1 INT GENERATED ALWAYS AS (0),
  c2 INT AS (0),
  c3 INT GENERATED ALWAYS AS (0) VIRTUAL,
  c4 INT AS (0) VIRTUAL,
  c5 INT GENERATED ALWAYS AS (0) STORED,
  c6 INT AS (0) STORED
);

-- Same as above, but with explicit NULL
CREATE TABLE t2 (
  c1 INT GENERATED ALWAYS AS (0) NULL,
  c2 INT AS (0) NULL,
  c3 INT GENERATED ALWAYS AS (0) VIRTUAL NULL,
  c4 INT AS (0) VIRTUAL NULL,
  c5 INT GENERATED ALWAYS AS (0) STORED NULL,
  c6 INT AS (0) STORED NULL
);

-- Same as above, but with explicit NOT NULL
CREATE TABLE t3 (
  c1 INT GENERATED ALWAYS AS (0) NOT NULL,
  c2 INT AS (0) NOT NULL,
  c3 INT GENERATED ALWAYS AS (0) VIRTUAL NOT NULL,
  c4 INT AS (0) VIRTUAL NOT NULL,
  c5 INT GENERATED ALWAYS AS (0) STORED NOT NULL,
  c6 INT AS (0) STORED NOT NULL
);
