CREATE TABLE t1 (
  id INT,
  a1 VARCHAR(12),
  a2 VARCHAR(12) COLLATE latin1_spanish_ci,
  b1 VARCHAR(12) CHARACTER SET utf8,
  b2 VARCHAR(12) CHARACTER SET utf8 COLLATE utf8_general_ci,
  b3 VARCHAR(12) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  c1 VARCHAR(12) CHARACTER SET utf8mb4,
  c2 VARCHAR(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  c3 VARCHAR(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  c4 ENUM('foo','bar','qux'),
  d TEXT,
  e TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  f MEDIUMTEXT,
  g LONGTEXT
) CHARACTER SET utf8;

CREATE TABLE t2 LIKE t1;
CREATE TABLE t3 LIKE t1;
CREATE TABLE t4 LIKE t1;
CREATE TABLE t5 LIKE t1;
CREATE TABLE t6 LIKE t1;
CREATE TABLE t7 LIKE t1;
CREATE TABLE t8 LIKE t1;
CREATE TABLE t9 LIKE t1;
CREATE TABLE t10 LIKE t1;

-- Convert individual columns
ALTER TABLE t1 MODIFY b1 VARCHAR(12) CHARACTER SET latin1;
ALTER TABLE t1 MODIFY b2 VARCHAR(12) COLLATE latin1_swedish_ci;
ALTER TABLE t1 MODIFY b3 VARCHAR(12) COLLATE latin1_spanish_ci;
ALTER TABLE t1 MODIFY c1 VARCHAR(12) CHARACTER SET utf8;
ALTER TABLE t1 MODIFY c2 VARCHAR(12) COLLATE utf8_general_ci;
ALTER TABLE t1 CHANGE c3 c3_copy VARCHAR(12) COLLATE utf8mb4_unicode_ci;
ALTER TABLE t1 MODIFY c4 ENUM('foo', 'bar', 'qux') COLLATE latin1_spanish_ci;

-- Change (default) table options
ALTER TABLE t2 CHARACTER SET = utf8;
ALTER TABLE t3 CHARACTER SET = latin1;
ALTER TABLE t4 COLLATE = utf8_general_ci;
ALTER TABLE t5 COLLATE = latin1_spanish_ci;
ALTER TABLE t6 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;

-- Convert the entire table at once
ALTER TABLE t7 CONVERT TO CHARACTER SET utf8;
ALTER TABLE t8 CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE t9 CONVERT TO CHARACTER SET latin1;
ALTER TABLE t10 CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
