CREATE TABLE t1 (id VARCHAR(12) PRIMARY) CHARACTER SET utf8;
CREATE TABLE t2 (id VARCHAR(12) PRIMARY, a VARCHAR(12)) CHARACTER SET utf8;
ALTER TABLE t2
  ADD CONSTRAINT a_fk
  FOREIGN KEY (a) REFERENCES t1 (id);

CREATE TABLE t3 (id VARCHAR(12) PRIMARY) CHARACTER SET utf8;
CREATE TABLE t4 (id VARCHAR(12) PRIMARY, a VARCHAR(12) CHARACTER SET utf8);
ALTER TABLE t4
  ADD CONSTRAINT a_fk
  FOREIGN KEY (a) REFERENCES t3 (id);
