CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(128),
  email VARCHAR(64)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE mailing_list (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(64) UNIQUE,
  UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE user_tokens (
  token VARCHAR(128) NOT NULL PRIMARY KEY,
  type VARCHAR(12) NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE exams (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  audio_url VARCHAR(128) NOT NULL,
  video_url VARCHAR(128) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE products (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  name VARCHAR(64) DEFAULT NULL,
  brand VARCHAR(64) DEFAULT NULL,
  img_url VARCHAR(128) DEFAULT NULL,
  options_power VARCHAR(2048),
  options_bc VARCHAR(2048),
  options_diameter VARCHAR(2048),
  options_cyl VARCHAR(2048),
  options_axis VARCHAR(2048),
  options_ot VARCHAR(2048),
  price_retail DECIMAL(13,2) DEFAULT 0,
  price_wholesale DECIMAL(13,2) DEFAULT 0,
  aab_code VARCHAR(12) NOT NULL DEFAULT '',
  description TEXT DEFAULT NULL,
  num_days_per_lens SMALLINT UNSIGNED DEFAULT 0,
  num_lenses SMALLINT UNSIGNED DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE scripts (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  left_power VARCHAR(32) DEFAULT NULL,
  left_bc VARCHAR(32) DEFAULT NULL,
  left_diameter VARCHAR(32) DEFAULT NULL,
  left_cyl VARCHAR(32) DEFAULT NULL,
  left_axis VARCHAR(32) DEFAULT NULL,
  left_ot VARCHAR(32) DEFAULT NULL,
  right_power VARCHAR(32) DEFAULT NULL,
  right_bc VARCHAR(32) DEFAULT NULL,
  right_diameter VARCHAR(32) DEFAULT NULL,
  right_cyl VARCHAR(32) DEFAULT NULL,
  right_axis VARCHAR(32) DEFAULT NULL,
  right_ot VARCHAR(32) DEFAULT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (product_id) REFERENCES products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE sessions (
  session_id varchar(255) COLLATE utf8_bin NOT NULL,
  expires int(11) unsigned NOT NULL,
  data text COLLATE utf8_bin,
  PRIMARY KEY (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE versions (
  to_version INT NOT NULL PRIMARY KEY,
  from_version INT NULL,
  date_migrated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `to_version` (`to_version`,`from_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
